// Optional: install Playwright, start the local server, then run this file.
const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const path = require('node:path');
const fs = require('node:fs');
const out = process.env.CAPTURE_DIR || path.join(require('node:os').tmpdir(), 'teshima-browser-check');
fs.mkdirSync(out,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL ? {channel:process.env.BROWSER_CHANNEL} : {})});
  const errors=[], failures=[];
  const context=await browser.newContext({viewport:{width:1100,height:700}});
  const page=await context.newPage();
  const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400) failures.push(r.url());});p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});};
  watch(page);
  const ready=async p=>{await p.goto(process.env.GAME_URL || 'http://127.0.0.1:8940');await p.waitForFunction(()=>typeof startReady!=='undefined'&&startReady&&texPending===0);};
  await ready(page);
  await page.screenshot({path:path.join(out,'title.jpg'),quality:65});
  await page.locator('#startBtn').click();
  await page.waitForTimeout(900);
  await page.keyboard.down('ArrowRight');
  assert.equal(await page.evaluate(()=>input.steer),1);
  assert.ok(await page.evaluate(()=>Math.abs(state.visualSteer)<1),'pose does not snap to full lean');
  await page.waitForTimeout(350);await page.keyboard.up('ArrowRight');
  assert.ok(await page.evaluate(()=>state.xOffset>0));assert.equal(await page.evaluate(()=>input.steer),0);
  await page.keyboard.down('ArrowDown');await page.waitForTimeout(1000);await page.keyboard.up('ArrowDown');
  assert.ok(await page.evaluate(()=>state.currentSpeed<CONFIG.speed*0.6),'brake reduces speed');
  await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>state.paused),true);
  const pausedDistance=await page.evaluate(()=>state.distance);await page.waitForTimeout(200);
  assert.equal(await page.evaluate(()=>state.distance),pausedDistance);
  await page.locator('#resumeBtn').click();assert.equal(await page.evaluate(()=>state.paused),false);
  await page.locator('#labBtn').click();assert.equal(await page.evaluate(()=>state.paused),true);
  await page.locator('#speedSlider').fill('54');assert.equal(await page.evaluate(()=>CONFIG.speed),54);
  assert.match(await page.locator('#labCode').textContent(),/speed: 54/);
  await page.locator('#steerSlider').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.evaluate(()=>input.steer),0,'range arrows do not steer');
  await page.screenshot({path:path.join(out,'lab.jpg'),quality:65});
  await page.locator('#labReset').click();assert.equal(await page.evaluate(()=>CONFIG.speed),36);
  await page.locator('#labClose').click();assert.equal(await page.evaluate(()=>state.paused),false);
  await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>state.paused),true);
  // Open the lab from a paused state using its underlying handler; preserve that state.
  await page.evaluate(()=>document.getElementById('labBtn').click());
  await page.locator('#labClose').click();assert.equal(await page.evaluate(()=>state.paused),true);
  await page.locator('#resumeBtn').click();
  await page.mouse.move(300,350);await page.mouse.down();assert.ok(await page.evaluate(()=>input.steer<0));
  await page.mouse.move(900,350);assert.ok(await page.evaluate(()=>input.steer>0));
  await page.mouse.move(550,350);assert.equal(await page.evaluate(()=>input.steer),0);
  await page.mouse.up();assert.equal(await page.evaluate(()=>canvasPointer),null);
  await page.keyboard.down('ArrowLeft');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  assert.equal(await page.evaluate(()=>state.paused),true);assert.equal(await page.evaluate(()=>input.steer),0);
  await page.keyboard.up('ArrowLeft');await page.locator('#resumeBtn').click();
  await page.evaluate(()=>{resetRun();state.running=true;});await page.waitForTimeout(1500);
  await page.evaluate(()=>state.paused=true);await page.screenshot({path:path.join(out,'coastal-ride.jpg'),quality:75});
  // Inspect later scenery after camera settles, without waiting for a complete lap.
  await page.evaluate(()=>{state.distance=205;state.paused=false});await page.waitForTimeout(1700);
  await page.evaluate(()=>state.paused=true);await page.screenshot({path:path.join(out,'curve.jpg'),quality:65});
  await page.evaluate(()=>{state.distance=state.totalLength-110;state.paused=false});await page.waitForTimeout(1500);
  await page.evaluate(()=>state.paused=true);await page.screenshot({path:path.join(out,'harbor.jpg'),quality:65});
  await page.evaluate(()=>{state.distance=state.totalLength-0.2;state.paused=false});
  await page.locator('#clearScreen').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>state.running),false);
  const geometryCount=await page.evaluate(()=>renderer.info.memory.geometries);
  await page.locator('#nextBtn').click();assert.equal(await page.evaluate(()=>state.lap),2);
  assert.ok(Math.abs(await page.evaluate(()=>state.speedScale)-1.08)<1e-8);
  assert.equal(await page.evaluate(()=>renderer.info.memory.geometries),geometryCount,'next lap reuses geometry');
  await page.evaluate(()=>state.paused=true);
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});
  const phone=await mobile.newPage();watch(phone);await ready(phone);await phone.locator('#startBtn').tap();
  const cdp=await mobile.newCDPSession(phone);
  const center=async selector=>{const b=await phone.locator(selector).boundingBox();return {x:b.x+b.width/2,y:b.y+b.height/2};};
  const left=await center('[data-control="left"]'),brake=await center('[data-control="brake"]');
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...left,id:1},{...brake,id:2}]});
  assert.equal(await phone.evaluate(()=>input.steer),-1);assert.equal(await phone.evaluate(()=>input.brake),true);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{...left,id:1}]});
  assert.equal(await phone.evaluate(()=>input.steer),0);assert.equal(await phone.evaluate(()=>input.brake),true);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  assert.equal(await phone.evaluate(()=>input.brake),false);assert.equal(await phone.evaluate(()=>pointerControls.size),0);
  await phone.waitForTimeout(800);await phone.evaluate(()=>state.paused=true);
  await phone.screenshot({path:path.join(out,'mobile.jpg'),quality:65});
  assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await phone.evaluate(()=>state.paused=false);await phone.locator('#labBtn').tap();
  await phone.locator('#speedSlider').fill('42');await phone.screenshot({path:path.join(out,'mobile-lab.jpg'),quality:65});
  await phone.locator('#labClose').tap();assert.equal(await phone.evaluate(()=>CONFIG.speed),42);
  await phone.setViewportSize({width:844,height:390});await phone.screenshot({path:path.join(out,'mobile-landscape.jpg'),quality:65});
  const reduced=await browser.newContext({viewport:{width:900,height:600},reducedMotion:'reduce'});
  const reducedPage=await reduced.newPage();watch(reducedPage);await ready(reducedPage);await reducedPage.locator('#startBtn').click();
  await reducedPage.keyboard.down('ArrowLeft');await reducedPage.waitForTimeout(350);
  assert.equal(await reducedPage.evaluate(()=>state.cameraBank),0);assert.equal(await reducedPage.evaluate(()=>camera.fov),62);
  assert.equal(await reducedPage.evaluate(()=>wind.particles.length),0);
  assert.deepEqual(failures,[]);assert.deepEqual(errors,[]);
  console.log('PASS: keyboard, smooth pose, brake, pause, lab, pointer drag, blur, goal, lap reuse, mobile multitouch/cancel, portrait/landscape and reduced motion.');
  console.log('Screenshots:',out);
  console.log('Render:',await page.evaluate(()=>({calls:renderer.info.render.calls,triangles:renderer.info.render.triangles})));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
